name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.104
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Common
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.Common/RedCounterSoftware.Common.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish DataAccess.EntityFrameworkCore.SqlServer
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.DataAccess.EntityFrameworkCore.SqlServer/RedCounterSoftware.DataAccess.EntityFrameworkCore.SqlServer.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish DataAccess.Dapper.SqlServer
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.DataAccess.Dapper.SqlServer/RedCounterSoftware.DataAccess.Dapper.SqlServer.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish DataAccess.RavenDb
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.DataAccess.RavenDb/RedCounterSoftware.DataAccess.RavenDb.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish Logging.Web
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.Logging.Web/RedCounterSoftware.Logging.Web.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish Mailing.SendGrid
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.Mailing.SendGrid/RedCounterSoftware.Mailing.SendGrid.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish Security.Jwt
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.Security.Jwt/RedCounterSoftware.Security.Jwt.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish Validation.FluentValidation
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.Validation.FluentValidation/RedCounterSoftware.Validation.FluentValidation.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
    - name: Publish WebApi
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: RedCounterSoftware.WebApi/RedCounterSoftware.WebApi.csproj
          NUGET_KEY: ${{secrets.NuGet}}
          INCLUDE_SYMBOLS: true
